### ISSUE TITLE
"Ticket #X" is displayed instead of ticket title in "CURRENT TICKETS" list

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Android#10]
my ticket title was "matt's first ticket" but "Ticket #0" is displayed. bug?

**Comment by ryanrampage1** [comment]
We really need to change this to create ticket numbers on the db

**Comment by ryanrampage1** [comment]
or just define display # based on some existing db field

**Comment by ryanrampage1** [comment]
changed it to display as whatever position in the list it is
