### ISSUE TITLE
helpdesk: tapping "submit" can leave valid fields red as if invalid

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Android#11]
##### steps to reproduce:
- load helpdesk pane
- immediately hit "submit" -- description field will turn red
- enter a description
- hit "submit" -- title field now turns red, and description field _remains_ red despite having content in it

**Comment by ryanrampage1** [comment]
@mhammerly cant reproduce this, when i do it the red box shifts to subject because the subject is empty so that is the error
