### ISSUE TITLE
subscribe/unsubscribe to push notifications graphic is cut off

### ISSUE THREAD

**Issue by jason-merlo** [SpartaHack/SpartaHack2016-Android#112]
![screenshot jan 8 2017 7-07-51 pm](https://cloud.githubusercontent.com/assets/2801596/21754829/4ab78962-d5d6-11e6-8be2-f2da8c1ede60.png)

**Comment by memuyskens** [comment]
This feature was moved to settings fragment in #144 and this bug is fixed in those changes.
