### ISSUE TITLE
Close the app (clear from Android's app switcher) and reopen; will start in pane you left off in, except the title will be "Notifications"

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Android#27]

**Comment by ryanrampage1** [comment]
somehow fucked up pending intents, after the app opened once it still has that p intent and always goes to the helpdesk fragment which is the default behavior of clicking a notificaion that is for helpdesk tickets

**Comment by ryanrampage1** [comment]
not worth fixing, closing issue
