### ISSUE TITLE
delete ticket form needs adjustment

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Android#47]
title should not be white text on light gray background?
there is a missing space after "for" -- the ticket title is still visible so maybe just say "Are you sure you want to delete this ticket?" or "Are you sure you want to delete your ticket 'ticket title'?"
![deletetickettypo](https://cloud.githubusercontent.com/assets/1198161/12877659/1854c128-cde5-11e5-8539-5d867078a232.png)

**Comment by ryanrampage1** [comment]
removed the icon and title part
