### ISSUE TITLE
not clear how to log in

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Android#5]
the header in the sidebar offers no indication that it is tappable or that it leads to a login screen. the helpdesk pane just says "needs authentication" -- if it's appropriate for the platform, perhaps when you load the helpdesk pane (or other authenticated panes) as an unauthenticated user it will prompt your to log in then and there.

**Comment by ryanrampage1** [comment]
added profile to navigation drawer
