### ISSUE TITLE
Suggestion: "Submit" button on top right corner of screen?

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Android#7]
this is a suggestion, not a demand, idk if this is compatible with platform conventions or good UX

my keyboard takes up half my screen, so when i'm filling out a ticket it covers up the "submit" button which is placed below the form. hiding the keyboard isn't the end of the world, i think folks should be able to figure that out, but if the button were placed in the top bar of the screen they wouldn't have to

**Comment by ryanrampage1** [comment]
fixed with new designs.
