### ISSUE TITLE
Add admin checkin like in iOS

### ISSUE THREAD

**Issue by ryanrampage1** [SpartaHack/SpartaHack2016-Android#93]

**Comment by mhammerly** [comment]
the scan feature exists in the menu when unauthenticated -- make sure it only shows when the user is signed in and they have the administrative role. does anything additional need to be exposed on the backend for you to get that information?

my admin account has role=1 in the database, and most users have 64. not sure what you would see it as, or if there are going to be more specific roles (maybe it's a bitmask idk)

**Comment by ryanrampage1** [comment]
I will add this later. should have explained that i just threw it in to test functionality of the scanner to start.

**Comment by ryanrampage1** [comment]
#125
