### ISSUE TITLE
logout button text is cut off at the bottom of the button

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Android#99]
2013 motorola moto x on android 5.1

![android_logout_bug](https://cloud.githubusercontent.com/assets/1198161/21366864/b281036e-c6c9-11e6-8c73-21ea59e4cd37.png)

**Comment by stokesdy** [comment]
Same issue for me except the slider is cut off a bit for Push Notifications

**Comment by memuyskens** [comment]
This was fixed in consistent_ui branch recently merged into develop.
